import { StyleSheet } from "react-native";

export const colors = {
  primary: "#137fec",
  disabled: "#cbd5e1",
  backgroundLight: "#F6FAFD",
  navyDark: "#0A1931",
  navyMedium: "#1A3D63",
  blueGray: "#4A7FA7",
  white: "#FFFFFF",
  slate50: "#f8fafc",
  error: "#FF0000",
  shadowColor: "rgba(0, 0, 0, 0.1)",
};

export const styles = StyleSheet.create({
  mainWrapper: { flex: 1, backgroundColor: colors.backgroundLight },
  header: {
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(26, 61, 99, 0.2)",
    elevation: 1,
    zIndex: 50,
  },
  headerContent: {
    maxWidth: 1200,
    width: "100%",
    alignSelf: "center",
    paddingHorizontal: 16,
    height: 64,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerContentWide: { paddingHorizontal: 24 },
  logoGroup: { flexDirection: "row", alignItems: "center", gap: 12 },
  logoImage: { width: 40, height: 40, resizeMode: "contain" },
  logoText: {
    color: colors.navyDark,
    fontSize: 18,
    fontWeight: "bold",
    lineHeight: 20,
  },
  logoSubtitle: { color: colors.blueGray, fontSize: 10, fontWeight: "500" },
  mainContent: {
    flex: 1,
    paddingVertical: 32,
    paddingHorizontal: 16,
  },
  mainContentWide: { paddingHorizontal: 24 },
  mainContentContainer: { paddingBottom: 32 },
  mainContentContainerMobileWeb: { paddingBottom: 120 },
  contentWrapper: {
    maxWidth: 960,
    alignSelf: "center",
    width: "100%",
    gap: 24,
  },
  breadcrumbs: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  breadcrumbLink: { color: colors.blueGray, fontSize: 14, fontWeight: "500" },
  breadcrumbSeparator: { color: colors.blueGray, fontSize: 12 },
  breadcrumbCurrent: { color: colors.navyDark, fontSize: 14, fontWeight: "bold" },
  pageTitle: {
    color: colors.navyDark,
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 36,
    textAlign: "center",
  },
  formCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 24,
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: "rgba(26, 61, 99, 0.3)",
  },
  formCardWide: { padding: 32 },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 8,
  },
  progressTitle: { color: colors.navyDark, fontSize: 16, fontWeight: "bold" },
  progressPercent: { color: colors.blueGray, fontSize: 14, fontWeight: "500" },
  progressBarOuter: {
    height: 8,
    width: "100%",
    borderRadius: 4,
    backgroundColor: colors.slate50,
    overflow: "hidden",
    marginBottom: 24,
  },
  progressBarInner: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  formRow: {
    flexDirection: "column",
    gap: 24,
    marginBottom: 16,
  },
  formRowWide: { flexDirection: "row" },
  inputLabel: {
    color: colors.navyDark,
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
  },
  inputWrapper: { flex: 1 },
  selectInput: {
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.navyMedium,
    backgroundColor: colors.slate50,
    paddingHorizontal: 16,
    justifyContent: "center",
  },
  docUploadContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  inputField: {
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.navyMedium,
    backgroundColor: colors.slate50,
    paddingHorizontal: 16,
    fontSize: 16,
    color: colors.navyDark,
  },
  phoneInputGroup: {
    flexDirection: "row",
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.navyMedium,
    backgroundColor: colors.slate50,
  },
  prefixButton: {
    width: 70,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: colors.navyMedium,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    paddingLeft: 4,
  },
  prefixButtonWide: { width: 90 },
  prefixText: { color: colors.navyDark, fontSize: 14, fontWeight: "bold" },
  numberInput: {
    flex: 1,
    paddingHorizontal: 16,
    fontSize: 16,
    color: colors.navyDark,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  cancelButtonText: { color: colors.blueGray, fontWeight: "bold" },
  continueButton: {
    width: "100%",
    height: 48,
    paddingHorizontal: 32,
    borderRadius: 8,
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  continueButtonWide: { width: "auto" },
  footerActions: {
    flexDirection: "column-reverse",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 16,
    marginTop: 16,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: "rgba(26, 61, 99, 0.3)",
  },
  footerActionsWide: { flexDirection: "row" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  modalContent: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 24,
    width: "100%",
    maxWidth: 400,
    elevation: 5,
  },
  modalOption: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: colors.slate50,
    borderWidth: 1,
    borderColor: colors.navyMedium,
  },
  modalOptionText: {
    fontSize: 16,
    color: colors.navyDark,
    textAlign: "center",
    fontWeight: "500",
  },
  inputError: { borderColor: colors.error, borderWidth: 1.5 },
  errorText: { color: colors.error, fontSize: 12, marginTop: 4, fontWeight: "500" },
  photoWrap: { alignItems: "center", marginBottom: 24 },
  photoCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.slate50,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "rgba(26, 61, 99, 0.3)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  photoImg: { width: "100%", height: "100%" },
  photoBtn: {
    marginTop: 12,
    height: 44,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(26, 61, 99, 0.3)",
    backgroundColor: colors.white,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  photoBtnText: { color: colors.blueGray, fontWeight: "bold" },
});
